---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: canopy-ui
  {{- if .Values.BACKEND_ENDPOINT}}
  annotations:
    app.openshift.io/connects-to: '[{"apiVersion":"apps/v1","kind":"Deployment","name":"canopy-backend"}]'
  {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: canopy-ui
      app.kubernetes.io/name: canopy-ui
  template:
    metadata:
      labels:
        app: canopy-ui
        app.kubernetes.io/name: canopy-ui
        monitoring.opendatahub.io/scrape: 'true'
    spec:
      serviceAccountName: canopy-fe
      containers:
        - name: canopy-ui
          image: quay.io/rhoai-genaiops/{{ .Values.image.name }}:{{ .Values.image.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: 8501
            - containerPort: 8000
          env:
           {{- if not .Values.BACKEND_ENDPOINT}}
            - name: LLM_ENDPOINT
              value: "{{ .Values.LLM_ENDPOINT }}"
            - name: MODEL_NAME
              value: "{{ .Values.MODEL_NAME }}"
          {{- else }}
            - name: BACKEND_ENDPOINT
              value: "{{ .Values.BACKEND_ENDPOINT }}"
          {{- end }}
            - name: MLFLOW_TRACKING_URI
              value: "{{ .Values.MLFLOW_TRACKING_URI }}"
            - name: MLFLOW_PROMPT_NAME
              value: "{{ .Values.MLFLOW_PROMPT_NAME | default "summarization" }}"
            - name: MLFLOW_PROMPT_VERSION
              value: "{{ .Values.MLFLOW_PROMPT_VERSION | default "latest" }}"
            - name: MLFLOW_TRACKING_INSECURE_TLS
              value: "true"

