---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: canopy-ui
spec:
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
  selector:
    matchLabels:
      app: canopy-ui
