FROM registry.access.redhat.com/ubi9/python-311

# Set working directory
WORKDIR /opt/app-root/src

# Copy files
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .

# Expose Streamlit default port and Prometheus metrics port
EXPOSE 8501
EXPOSE 8000

# Run app
CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]
# CMD ["streamlit", "run", "simple_app.py", "--server.port=8501", "--server.address=0.0.0.0"]